---
env:
  node: true
  es2021: true

extends:
  - 'eslint:recommended'
  - 'prettier'

ignorePatterns:
  - coverage
  - dist
  - node_modules

overrides:
  - files: '**/?(*.)+(spec|test).js'
    env:
      jest: true

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'

rules:
  indent:
    - error
    - 2
    - { SwitchCase: 1 }

  linebreak-style:
    - error
    - 'unix'

  quotes:
    - error
    - 'single'

  semi:
    - error
    - 'never'
